id: P2278B1B6
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN9311
  title: དཔལ་དགེ་ལྡན་པའི་ལམ་རིམ་དང་སྙན་བརྒྱུད་ཀྱི་ཆོས་སྐོར།
  volumes:
    9009edf34dc04264ba5c69f06ea5a92b:
      image_group_id: I3CN9313
      title: ''
      base_file: v001.txt
  author: ''
